// SPDX-License-Identifier: Apache-2.0

package graphwire

import (
	"fmt"
	"sort"
	"strings"
)

// generatedHeader renders the SPDX and generated-code header for license.
func generatedHeader(license string) string {
	return "// SPDX-License-Identifier: " + license + "\n\n" +
		"// Code generated by pluginwire. DO NOT EDIT.\n\n"
}

// generate renders the unformatted resolver root wiring file.
func generate(cfg Config, core contributor, plugins []contributor) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader(cfg.License))
	b.WriteString("package main\n\n")
	writeImports(&b, cfg, plugins)
	if len(plugins) == 0 {
		b.WriteString("// newGraphRoot returns the core resolver root, no plugin extends the graph.\n")
		b.WriteString("func newGraphRoot(core graph.ResolverRoot) graph.ResolverRoot {\n\treturn core\n}\n")
		return []byte(b.String())
	}
	writeContributorInterface(&b, core, "the core contributes to the graph")
	for _, plugin := range plugins {
		writeContributorInterface(&b, plugin, "the "+plugin.field+" plugin contributes to the graph")
	}
	types, contributorsOf := typeContributors(core, plugins)
	writeComposites(&b, types, contributorsOf)
	writeRoot(&b, core, plugins)
	writeAccessors(&b, types, contributorsOf)
	return []byte(b.String())
}

// writeImports renders the aliased import block sorted by import path.
func writeImports(b *strings.Builder, cfg Config, plugins []contributor) {
	type imported struct{ alias, path string }
	imports := []imported{{"graph", cfg.ExecImport}}
	if len(plugins) > 0 {
		imports = append(imports, imported{goName(pathBase(cfg.CoreImport)), cfg.CoreImport})
	}
	for _, plugin := range plugins {
		imports = append(imports, imported{plugin.alias, plugin.path})
	}
	sort.Slice(imports, func(i, j int) bool { return imports[i].path < imports[j].path })
	b.WriteString("import (\n")
	for _, entry := range imports {
		fmt.Fprintf(b, "\t%s %q\n", entry.alias, entry.path)
	}
	b.WriteString(")\n\n")
}

// pathBase returns the last segment of an import path.
func pathBase(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}
	return path
}

// writeContributorInterface renders one contributor's resolver set interface.
func writeContributorInterface(b *strings.Builder, c contributor, owner string) {
	fmt.Fprintf(b, "// %sGraphResolvers lists the resolver sets %s.\n", c.field, owner)
	fmt.Fprintf(b, "type %sGraphResolvers interface {\n", c.field)
	for _, typeName := range c.types {
		fmt.Fprintf(b, "\t%sResolvers() %s.%sResolvers\n", typeName, c.alias, typeName)
	}
	b.WriteString("}\n\n")
}

// typeContributors returns every contributed type and its contributors in order.
func typeContributors(core contributor, plugins []contributor) ([]string, map[string][]contributor) {
	contributorsOf := map[string][]contributor{}
	for _, typeName := range core.types {
		contributorsOf[typeName] = append(contributorsOf[typeName], core)
	}
	for _, plugin := range plugins {
		for _, typeName := range plugin.types {
			contributorsOf[typeName] = append(contributorsOf[typeName], plugin)
		}
	}
	types := make([]string, 0, len(contributorsOf))
	for typeName := range contributorsOf {
		types = append(types, typeName)
	}
	sort.Strings(types)
	return types, contributorsOf
}

// writeComposites renders one merged resolver struct per shared type.
func writeComposites(b *strings.Builder, types []string, contributorsOf map[string][]contributor) {
	for _, typeName := range types {
		contributors := contributorsOf[typeName]
		if len(contributors) < 2 {
			continue
		}
		fmt.Fprintf(b, "// composed%sResolver merges every contributed %s resolver set.\n", typeName, typeName)
		fmt.Fprintf(b, "type composed%sResolver struct {\n", typeName)
		for _, c := range contributors {
			fmt.Fprintf(b, "\t%s.%sResolvers\n", c.alias, typeName)
		}
		b.WriteString("}\n\n")
	}
}

// writeRoot renders the root type and its constructor.
func writeRoot(b *strings.Builder, core contributor, plugins []contributor) {
	b.WriteString("// graphRoot composes the core and plugin resolver sets into the resolver root.\n")
	b.WriteString("type graphRoot struct {\n")
	fmt.Fprintf(b, "\t%s %sGraphResolvers\n", core.field, core.field)
	for _, plugin := range plugins {
		fmt.Fprintf(b, "\t%s %sGraphResolvers\n", plugin.field, plugin.field)
	}
	b.WriteString("}\n\n")
	b.WriteString("// newGraphRoot composes the core resolver sets with every graphql plugin's.\n")
	b.WriteString("func newGraphRoot(\n")
	fmt.Fprintf(b, "\t%s %sGraphResolvers,\n", core.param, core.field)
	for _, plugin := range plugins {
		fmt.Fprintf(b, "\t%s %sGraphResolvers,\n", plugin.param, plugin.field)
	}
	b.WriteString(") graph.ResolverRoot {\n\treturn graphRoot{")
	assignments := []string{core.field + ": " + core.param}
	for _, plugin := range plugins {
		assignments = append(assignments, plugin.field+": "+plugin.param)
	}
	b.WriteString(strings.Join(assignments, ", "))
	b.WriteString("}\n}\n\n")
}

// writeAccessors renders one ResolverRoot accessor per contributed type.
func writeAccessors(b *strings.Builder, types []string, contributorsOf map[string][]contributor) {
	for i, typeName := range types {
		fmt.Fprintf(b, "// %s returns the %s resolver set.\n", typeName, typeName)
		fmt.Fprintf(b, "func (g graphRoot) %s() graph.%sResolver {\n", typeName, typeName)
		contributors := contributorsOf[typeName]
		if len(contributors) == 1 {
			fmt.Fprintf(b, "\treturn g.%s.%sResolvers()\n", contributors[0].field, typeName)
		} else {
			fmt.Fprintf(b, "\treturn composed%sResolver{\n", typeName)
			for _, c := range contributors {
				fmt.Fprintf(b, "\t\tg.%s.%sResolvers(),\n", c.field, typeName)
			}
			b.WriteString("\t}\n")
		}
		b.WriteString("}\n")
		if i < len(types)-1 {
			b.WriteString("\n")
		}
	}
}
