// SPDX-License-Identifier: Apache-2.0

package graphwire

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var testConfig = Config{
	ExecImport:      "example.com/myapp/graph",
	CoreImport:      "example.com/myapp/internal/graphres",
	CoreSchemaGlobs: []string{"graph/schema/*.graphqls"},
	WiringPath:      "cmd/myapp/graph_gen.go",
	License:         "Apache-2.0",
}

const coreSchema = `
directive @goField(forceResolver: Boolean, name: String) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

type Query {
	things: [Thing!]!
}

type Mutation {
	makeThing(name: String!): Thing!
}

type Thing {
	id: ID!
	name: String!
	owner: Owner @goField(forceResolver: true)
}

type Owner {
	id: ID!
	things(limit: Int): [Thing!]!
}
`

const alphaSchema = `
extend type Query {
	alphaItems: [AlphaItem!]!
}

type AlphaItem {
	id: ID!
	thing: Thing @goField(forceResolver: true)
}

extend type Thing {
	alphaItems: [AlphaItem!]! @goField(forceResolver: true)
}
`

const betaSchema = `
extend type Query {
	betaCount: Int!
}
`

// writeCore writes the core schema fixture under root.
func writeCore(t *testing.T, root string) {
	t.Helper()
	dir := filepath.Join(root, "graph", "schema")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", dir, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "core.graphqls"), []byte(coreSchema), 0o644); err != nil {
		t.Fatalf("writing core schema: %v", err)
	}
}

// writePlugin writes a plugin fixture with a manifest and optional SDL.
func writePlugin(t *testing.T, root, id, manifestJSON, sdl string) {
	t.Helper()
	pluginDir := filepath.Join(root, "plugins", id)
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", pluginDir, err)
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "plugin.json"), []byte(manifestJSON), 0o644); err != nil {
		t.Fatalf("writing manifest: %v", err)
	}
	if sdl == "" {
		return
	}
	graphDir := filepath.Join(pluginDir, "graph")
	if err := os.MkdirAll(graphDir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", graphDir, err)
	}
	if err := os.WriteFile(filepath.Join(graphDir, "schema.graphqls"), []byte(sdl), 0o644); err != nil {
		t.Fatalf("writing plugin schema: %v", err)
	}
}

// generated runs the generator and returns the wiring file contents.
func generated(t *testing.T, root string) string {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(root, "cmd", "myapp"), 0o755); err != nil {
		t.Fatalf("creating the output directory: %v", err)
	}
	if err := Run(root, testConfig); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}
	content, err := os.ReadFile(filepath.Join(root, "cmd", "myapp", "graph_gen.go"))
	if err != nil {
		t.Fatalf("reading the wiring file: %v", err)
	}
	return string(content)
}

const zeroPluginWiring = `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	graph "example.com/myapp/graph"
)

// newGraphRoot returns the core resolver root, no plugin extends the graph.
func newGraphRoot(core graph.ResolverRoot) graph.ResolverRoot {
	return core
}
`

func TestZeroGraphQLPluginsYieldACoreOnlyRoot(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "feed",
		`{"id": "feed", "name": "Feed", "backend": "example.com/myapp/plugins/feed"}`, "")

	if got := generated(t, root); got != zeroPluginWiring {
		t.Errorf("wiring mismatch\n got:\n%s\nwant:\n%s", got, zeroPluginWiring)
	}
}

const composedWiring = `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	graph "example.com/myapp/graph"
	graphres "example.com/myapp/internal/graphres"
	alpha "example.com/myapp/plugins/alpha"
	beta "example.com/myapp/plugins/beta"
)

// coreGraphResolvers lists the resolver sets the core contributes to the graph.
type coreGraphResolvers interface {
	MutationResolvers() graphres.MutationResolvers
	OwnerResolvers() graphres.OwnerResolvers
	QueryResolvers() graphres.QueryResolvers
	ThingResolvers() graphres.ThingResolvers
}

// alphaGraphResolvers lists the resolver sets the alpha plugin contributes to the graph.
type alphaGraphResolvers interface {
	AlphaItemResolvers() alpha.AlphaItemResolvers
	QueryResolvers() alpha.QueryResolvers
	ThingResolvers() alpha.ThingResolvers
}

// betaGraphResolvers lists the resolver sets the beta plugin contributes to the graph.
type betaGraphResolvers interface {
	QueryResolvers() beta.QueryResolvers
}

// composedQueryResolver merges every contributed Query resolver set.
type composedQueryResolver struct {
	graphres.QueryResolvers
	alpha.QueryResolvers
	beta.QueryResolvers
}

// composedThingResolver merges every contributed Thing resolver set.
type composedThingResolver struct {
	graphres.ThingResolvers
	alpha.ThingResolvers
}

// graphRoot composes the core and plugin resolver sets into the resolver root.
type graphRoot struct {
	core  coreGraphResolvers
	alpha alphaGraphResolvers
	beta  betaGraphResolvers
}

// newGraphRoot composes the core resolver sets with every graphql plugin's.
func newGraphRoot(
	core coreGraphResolvers,
	alphaPlugin alphaGraphResolvers,
	betaPlugin betaGraphResolvers,
) graph.ResolverRoot {
	return graphRoot{core: core, alpha: alphaPlugin, beta: betaPlugin}
}

// AlphaItem returns the AlphaItem resolver set.
func (g graphRoot) AlphaItem() graph.AlphaItemResolver {
	return g.alpha.AlphaItemResolvers()
}

// Mutation returns the Mutation resolver set.
func (g graphRoot) Mutation() graph.MutationResolver {
	return g.core.MutationResolvers()
}

// Owner returns the Owner resolver set.
func (g graphRoot) Owner() graph.OwnerResolver {
	return g.core.OwnerResolvers()
}

// Query returns the Query resolver set.
func (g graphRoot) Query() graph.QueryResolver {
	return composedQueryResolver{
		g.core.QueryResolvers(),
		g.alpha.QueryResolvers(),
		g.beta.QueryResolvers(),
	}
}

// Thing returns the Thing resolver set.
func (g graphRoot) Thing() graph.ThingResolver {
	return composedThingResolver{
		g.core.ThingResolvers(),
		g.alpha.ThingResolvers(),
	}
}
`

const alphaManifest = `{
	"id": "alpha", "name": "Alpha",
	"backend": "example.com/myapp/plugins/alpha", "graphql": true
}`

func TestPluginsComposeWithTheCoreSets(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "alpha", alphaManifest, alphaSchema)
	writePlugin(t, root, "beta",
		`{"id": "beta", "name": "Beta", "backend": "example.com/myapp/plugins/beta", "graphql": true}`,
		betaSchema)

	if got := generated(t, root); got != composedWiring {
		t.Errorf("wiring mismatch\n got:\n%s\nwant:\n%s", got, composedWiring)
	}
}

func TestUnflaggedPluginsContributeNothing(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "alpha", alphaManifest, alphaSchema)
	writePlugin(t, root, "beta",
		`{"id": "beta", "name": "Beta", "backend": "example.com/myapp/plugins/beta"}`,
		betaSchema)

	if got := generated(t, root); strings.Contains(got, "beta") {
		t.Errorf("wiring mentions the unflagged beta plugin:\n%s", got)
	}
}

func TestUnreadableSDLFailsLoudly(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "alpha", alphaManifest, "type {{{ nope")

	err := Run(root, testConfig)

	if err == nil || !strings.Contains(err.Error(), "schema.graphqls") {
		t.Errorf("Run() error = %v, want the failing SDL path named", err)
	}
}

func TestFlaggedPluginWithoutSchemaFails(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "alpha", alphaManifest, "")

	err := Run(root, testConfig)

	if err == nil || !strings.Contains(err.Error(), "graph/*.graphqls") {
		t.Errorf("Run() error = %v, want the missing SDL reported", err)
	}
}

func TestGraphQLPluginsRequireABackend(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCore(t, root)
	writePlugin(t, root, "alpha",
		`{"id": "alpha", "name": "Alpha", "frontend": "@myapp/alpha", "graphql": true}`,
		alphaSchema)

	err := Run(root, testConfig)

	if err == nil || !strings.Contains(err.Error(), "backend") {
		t.Errorf("Run() error = %v, want the missing backend reported", err)
	}
}
