// SPDX-License-Identifier: Apache-2.0

// Package wire generates an application's plugin wiring files from the
// plugin.json manifest of every directory under plugins/.
package wire

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Config parameterizes generation for the consuming application.
type Config struct {
	SDKImport    string
	FrontendSDK  string
	GoWiringPath string
	TSWiringPath string
	License      string
	TSLicense    string
}

// tsLicense returns the license for the TypeScript wiring file.
func (c Config) tsLicense() string {
	if c.TSLicense != "" {
		return c.TSLicense
	}
	return c.License
}

// validateConfig checks that every Config field is set.
func validateConfig(cfg Config) error {
	if cfg.SDKImport == "" || cfg.FrontendSDK == "" || cfg.GoWiringPath == "" ||
		cfg.TSWiringPath == "" || cfg.License == "" {
		return errors.New("wire: every Config field is required")
	}
	return nil
}

type manifest struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Backend  string `json:"backend"`
	Frontend string `json:"frontend"`
}

var idPattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

// loadManifests loads and validates the plugin manifest in each subdirectory of dir.
func loadManifests(dir string) ([]manifest, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("pluginwire: reading plugins directory: %w", err)
	}
	manifests := make([]manifest, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		path := filepath.Join(dir, entry.Name(), "plugin.json")
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		var m manifest
		if err := json.Unmarshal(data, &m); err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		if err := validate(m, entry.Name()); err != nil {
			return nil, fmt.Errorf("pluginwire: %s: %w", path, err)
		}
		manifests = append(manifests, m)
	}
	return manifests, nil
}

// validate checks that manifest m has a well-formed id matching dir, a name, and at least one of backend or frontend.
func validate(m manifest, dir string) error {
	if !idPattern.MatchString(m.ID) {
		return fmt.Errorf("id %q must match %s", m.ID, idPattern)
	}
	if m.ID != dir {
		return fmt.Errorf("id %q does not match directory %q", m.ID, dir)
	}
	if m.Name == "" {
		return errors.New("name is required")
	}
	if m.Backend == "" && m.Frontend == "" {
		return errors.New("at least one of backend or frontend is required")
	}
	return nil
}

// goName returns id as a valid Go identifier.
func goName(id string) string {
	return strings.ReplaceAll(id, "-", "_")
}

// generatedHeader renders the SPDX and generated-code header for license.
func generatedHeader(license string) string {
	return "// SPDX-License-Identifier: " + license + "\n\n" +
		"// Code generated by pluginwire. DO NOT EDIT.\n\n"
}

// generateGo renders the generated Go plugin-wiring file.
func generateGo(cfg Config, manifests []manifest) []byte {
	backends := make([]manifest, 0, len(manifests))
	for _, m := range manifests {
		if m.Backend != "" {
			backends = append(backends, m)
		}
	}

	var b strings.Builder
	b.WriteString(generatedHeader(cfg.License))
	b.WriteString("package main\n\nimport (\n")
	for _, m := range backends {
		fmt.Fprintf(&b, "\t%s %q\n", goName(m.ID), m.Backend)
	}
	if len(backends) > 0 {
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "\t%q\n)\n\n", cfg.SDKImport)
	if len(backends) == 0 {
		b.WriteString("func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {\n\treturn []sdk.Plugin{}, nil\n}\n")
		return []byte(b.String())
	}
	fmt.Fprintf(
		&b,
		"func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {\n\tplugins := make([]sdk.Plugin, 0, %d)\n",
		len(backends),
	)
	for _, m := range backends {
		name := goName(m.ID)
		fmt.Fprintf(
			&b,
			"\t%sPlugin, err := %s.Register(deps)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n"+
				"\tplugins = append(plugins, %sPlugin)\n",
			name,
			name,
			name,
		)
	}
	b.WriteString("\treturn plugins, nil\n}\n")
	return []byte(b.String())
}

// generateTS renders the generated TypeScript plugin-wiring file.
func generateTS(cfg Config, manifests []manifest) []byte {
	frontends := make([]manifest, 0, len(manifests))
	for _, m := range manifests {
		if m.Frontend != "" {
			frontends = append(frontends, m)
		}
	}

	var b strings.Builder
	b.WriteString(generatedHeader(cfg.tsLicense()))
	fmt.Fprintf(&b, "import type { FrontendPlugin } from '%s'\n", cfg.FrontendSDK)
	names := make([]string, 0, len(frontends))
	for _, m := range frontends {
		name := goName(m.ID)
		names = append(names, name)
		fmt.Fprintf(&b, "import { plugin as %s } from '%s'\n", name, m.Frontend)
	}
	fmt.Fprintf(&b, "\nexport const plugins: FrontendPlugin[] = [%s]\n", strings.Join(names, ", "))
	return []byte(b.String())
}

// Run loads the plugin manifests under root and writes the application's
// generated Go and TypeScript wiring files per cfg.
func Run(root string, cfg Config) error {
	if err := validateConfig(cfg); err != nil {
		return err
	}
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		return err
	}
	goPath := filepath.Join(root, filepath.FromSlash(cfg.GoWiringPath))
	if err := os.WriteFile(goPath, generateGo(cfg, manifests), 0o644); err != nil {
		return fmt.Errorf("pluginwire: %w", err)
	}
	tsPath := filepath.Join(root, filepath.FromSlash(cfg.TSWiringPath))
	if err := os.WriteFile(tsPath, generateTS(cfg, manifests), 0o644); err != nil {
		return fmt.Errorf("pluginwire: %w", err)
	}
	return nil
}
