// SPDX-License-Identifier: Apache-2.0

package wire

import (
	"os"
	"path/filepath"
	"testing"
)

var testConfig = Config{
	SDKImport:    "example.com/myapp/sdk",
	FrontendSDK:  "@myapp/frontend-sdk",
	GoWiringPath: "cmd/myapp/plugins_gen.go",
	TSWiringPath: "frontend/src/plugins/index.ts",
	License:      "Apache-2.0",
}

const feedManifest = `{
	"id": "feed",
	"name": "Feed",
	"backend": "example.com/myapp/plugins/feed",
	"frontend": "@myapp/plugin-feed"
}`

func writePlugin(t *testing.T, root, dir, manifestJSON string) {
	t.Helper()
	pluginDir := filepath.Join(root, "plugins", dir)
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", pluginDir, err)
	}
	if manifestJSON == "" {
		return
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "plugin.json"), []byte(manifestJSON), 0o644); err != nil {
		t.Fatalf("writing manifest: %v", err)
	}
}

func TestLoadManifestsReadsValidPlugins(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "photo-gallery",
		`{"id": "photo-gallery", "name": "Photo Gallery", "backend": "example.com/gallery"}`)
	writePlugin(t, root, "feed", feedManifest)
	if err := os.WriteFile(filepath.Join(root, "plugins", "README.md"), []byte("not a plugin"), 0o644); err != nil {
		t.Fatalf("writing stray file: %v", err)
	}

	manifests, err := loadManifests(filepath.Join(root, "plugins"))

	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if len(manifests) != 2 {
		t.Fatalf("manifests = %d, want 2", len(manifests))
	}
	if manifests[0].ID != "feed" || manifests[1].ID != "photo-gallery" {
		t.Errorf("order = [%q, %q], want directory order [%q, %q]",
			manifests[0].ID, manifests[1].ID, "feed", "photo-gallery")
	}
	if manifests[0].Backend != "example.com/myapp/plugins/feed" {
		t.Errorf("backend = %q, want the module import path", manifests[0].Backend)
	}
	if manifests[0].Frontend != "@myapp/plugin-feed" {
		t.Errorf("frontend = %q, want the npm package name", manifests[0].Frontend)
	}
}

func TestLoadManifestsRejectsInvalidPlugins(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		dir      string
		manifest string
	}{
		"missing manifest": {dir: "ghost", manifest: ""},
		"malformed json":   {dir: "broken", manifest: `{`},
		"missing id":       {dir: "anon", manifest: `{"name": "Anon", "backend": "example.com/anon"}`},
		"uppercase id": {
			dir:      "Loud",
			manifest: `{"id": "Loud", "name": "Loud", "backend": "example.com/loud"}`,
		},
		"id and directory disagree": {
			dir:      "alias",
			manifest: `{"id": "other", "name": "Alias", "backend": "example.com/alias"}`,
		},
		"missing name":                 {dir: "nameless", manifest: `{"id": "nameless", "backend": "example.com/nameless"}`},
		"neither backend nor frontend": {dir: "hollow", manifest: `{"id": "hollow", "name": "Hollow"}`},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, tc.dir, tc.manifest)

			if _, err := loadManifests(filepath.Join(root, "plugins")); err == nil {
				t.Fatal("loadManifests() error = nil, want a validation error")
			}
		})
	}
}

func TestGenerateGoWiresBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo(testConfig, []manifest{
		{ID: "photo-gallery", Name: "Photo Gallery", Backend: "example.com/gallery"},
		{
			ID:       "feed",
			Name:     "Feed",
			Backend:  "example.com/myapp/plugins/feed",
			Frontend: "@myapp/plugin-feed",
		},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	photo_gallery "example.com/gallery"
	feed "example.com/myapp/plugins/feed"

	"example.com/myapp/sdk"
)

func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 2)
	photo_galleryPlugin, err := photo_gallery.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, photo_galleryPlugin)
	feedPlugin, err := feed.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, feedPlugin)
	return plugins, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateGoWithoutBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo(testConfig, []manifest{
		{ID: "pretty", Name: "Pretty", Frontend: "@myapp/plugin-pretty"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	"example.com/myapp/sdk"
)

func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {
	return []sdk.Plugin{}, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateTSWiresFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS(testConfig, []manifest{
		{
			ID:       "photo-gallery",
			Name:     "Photo Gallery",
			Backend:  "example.com/gallery",
			Frontend: "@myapp/plugin-photo-gallery",
		},
		{ID: "feed", Name: "Feed", Frontend: "@myapp/plugin-feed"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@myapp/frontend-sdk'
import { plugin as photo_gallery } from '@myapp/plugin-photo-gallery'
import { plugin as feed } from '@myapp/plugin-feed'

export const plugins: FrontendPlugin[] = [photo_gallery, feed]
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestGenerateTSWithoutFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS(testConfig, []manifest{
		{ID: "headless", Name: "Headless", Backend: "example.com/headless"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@myapp/frontend-sdk'

export const plugins: FrontendPlugin[] = []
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestRunWritesWiringFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	for _, dir := range []string{"cmd/myapp", "frontend/src/plugins"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}

	if err := Run(root, testConfig); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}

	goSrc, err := os.ReadFile(filepath.Join(root, "cmd", "myapp", "plugins_gen.go"))
	if err != nil {
		t.Fatalf("reading generated Go wiring: %v", err)
	}
	tsSrc, err := os.ReadFile(filepath.Join(root, "frontend", "src", "plugins", "index.ts"))
	if err != nil {
		t.Fatalf("reading generated TS wiring: %v", err)
	}
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if string(goSrc) != string(generateGo(testConfig, manifests)) {
		t.Errorf("plugins_gen.go = %q, want the generated wiring", goSrc)
	}
	if string(tsSrc) != string(generateTS(testConfig, manifests)) {
		t.Errorf("index.ts = %q, want the generated registry", tsSrc)
	}
}

func TestRunRejectsIncompleteConfig(t *testing.T) {
	t.Parallel()

	tests := map[string]func(cfg Config) Config{
		"missing sdk import":     func(cfg Config) Config { cfg.SDKImport = ""; return cfg },
		"missing frontend sdk":   func(cfg Config) Config { cfg.FrontendSDK = ""; return cfg },
		"missing go wiring path": func(cfg Config) Config { cfg.GoWiringPath = ""; return cfg },
		"missing ts wiring path": func(cfg Config) Config { cfg.TSWiringPath = ""; return cfg },
		"missing license":        func(cfg Config) Config { cfg.License = ""; return cfg },
	}

	for testName, mutate := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, "feed", feedManifest)

			if err := Run(root, mutate(testConfig)); err == nil {
				t.Fatal("Run() error = nil, want a config validation error")
			}
		})
	}
}

func TestRunReportsFailures(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		prepare func(t *testing.T, root string)
	}{
		"missing plugins directory": {
			prepare: func(_ *testing.T, _ string) {},
		},
		"unwritable go wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "feed", feedManifest)
			},
		},
		"unwritable ts wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "feed", feedManifest)
				if err := os.MkdirAll(filepath.Join(root, "cmd", "myapp"), 0o755); err != nil {
					t.Fatalf("creating cmd/myapp: %v", err)
				}
			},
		},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			tc.prepare(t, root)

			if err := Run(root, testConfig); err == nil {
				t.Fatal("Run() error = nil, want an error")
			}
		})
	}
}
