// SPDX-License-Identifier: Apache-2.0

package wire

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var testConfig = Config{
	SDKImport:    "example.com/myapp/sdk",
	FrontendSDK:  "@myapp/frontend-sdk",
	GoWiringPath: "cmd/myapp/plugins_gen.go",
	TSWiringPath: "frontend/src/plugins/index.ts",
	License:      "Apache-2.0",
}

const feedManifest = `{
	"id": "feed",
	"name": "Feed",
	"backend": "example.com/myapp/plugins/feed",
	"frontend": "@myapp/plugin-feed"
}`

func writePlugin(t *testing.T, root, dir, manifestJSON string) {
	t.Helper()
	writePluginIn(t, root, "plugins", dir, manifestJSON)
}

func writePluginIn(t *testing.T, root, pluginRoot, dir, manifestJSON string) {
	t.Helper()
	pluginDir := filepath.Join(root, pluginRoot, dir)
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatalf("creating %s: %v", pluginDir, err)
	}
	if manifestJSON == "" {
		return
	}
	if err := os.WriteFile(filepath.Join(pluginDir, "plugin.json"), []byte(manifestJSON), 0o644); err != nil {
		t.Fatalf("writing manifest: %v", err)
	}
}

func TestLoadManifestsReadsValidPlugins(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "photo-gallery",
		`{"id": "photo-gallery", "name": "Photo Gallery", "backend": "example.com/gallery"}`)
	writePlugin(t, root, "feed", feedManifest)
	if err := os.WriteFile(filepath.Join(root, "plugins", "README.md"), []byte("not a plugin"), 0o644); err != nil {
		t.Fatalf("writing stray file: %v", err)
	}

	manifests, err := loadManifests(filepath.Join(root, "plugins"))

	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if len(manifests) != 2 {
		t.Fatalf("manifests = %d, want 2", len(manifests))
	}
	if manifests[0].ID != "feed" || manifests[1].ID != "photo-gallery" {
		t.Errorf("order = [%q, %q], want directory order [%q, %q]",
			manifests[0].ID, manifests[1].ID, "feed", "photo-gallery")
	}
	if manifests[0].Backend != "example.com/myapp/plugins/feed" {
		t.Errorf("backend = %q, want the module import path", manifests[0].Backend)
	}
	if manifests[0].Frontend != "@myapp/plugin-feed" {
		t.Errorf("frontend = %q, want the npm package name", manifests[0].Frontend)
	}
}

func TestLoadManifestsRejectsInvalidPlugins(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		dir      string
		manifest string
	}{
		"missing manifest": {dir: "ghost", manifest: ""},
		"malformed json":   {dir: "broken", manifest: `{`},
		"missing id":       {dir: "anon", manifest: `{"name": "Anon", "backend": "example.com/anon"}`},
		"uppercase id": {
			dir:      "Loud",
			manifest: `{"id": "Loud", "name": "Loud", "backend": "example.com/loud"}`,
		},
		"id and directory disagree": {
			dir:      "alias",
			manifest: `{"id": "other", "name": "Alias", "backend": "example.com/alias"}`,
		},
		"missing name":                 {dir: "nameless", manifest: `{"id": "nameless", "backend": "example.com/nameless"}`},
		"neither backend nor frontend": {dir: "hollow", manifest: `{"id": "hollow", "name": "Hollow"}`},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, tc.dir, tc.manifest)

			if _, err := loadManifests(filepath.Join(root, "plugins")); err == nil {
				t.Fatal("loadManifests() error = nil, want a validation error")
			}
		})
	}
}

func TestGenerateGoWiresBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo(testConfig, []manifest{
		{ID: "photo-gallery", Name: "Photo Gallery", Backend: "example.com/gallery"},
		{
			ID:       "feed",
			Name:     "Feed",
			Backend:  "example.com/myapp/plugins/feed",
			Frontend: "@myapp/plugin-feed",
		},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	photo_gallery "example.com/gallery"
	feed "example.com/myapp/plugins/feed"

	"example.com/myapp/sdk"
)

func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 2)
	photo_galleryPlugin, err := photo_gallery.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, photo_galleryPlugin)
	feedPlugin, err := feed.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, feedPlugin)
	return plugins, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateGoWithoutBackendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateGo(testConfig, []manifest{
		{ID: "pretty", Name: "Pretty", Frontend: "@myapp/plugin-pretty"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	"example.com/myapp/sdk"
)

func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {
	return []sdk.Plugin{}, nil
}
`
	if got != want {
		t.Errorf("generateGo() = %q, want %q", got, want)
	}
}

func TestGenerateTSWiresFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS(testConfig, []manifest{
		{
			ID:       "photo-gallery",
			Name:     "Photo Gallery",
			Backend:  "example.com/gallery",
			Frontend: "@myapp/plugin-photo-gallery",
		},
		{ID: "feed", Name: "Feed", Frontend: "@myapp/plugin-feed"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@myapp/frontend-sdk'
import { plugin as photo_gallery } from '@myapp/plugin-photo-gallery'
import { plugin as feed } from '@myapp/plugin-feed'

export const plugins: FrontendPlugin[] = [photo_gallery, feed]
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestGenerateTSUsesTSLicenseWhenSet(t *testing.T) {
	t.Parallel()

	cfg := testConfig
	cfg.TSLicense = "AGPL-3.0-or-later"

	goSrc := string(generateGo(cfg, []manifest{{ID: "feed", Name: "Feed", Backend: "example.com/myapp/plugins/feed"}}))
	tsSrc := string(generateTS(cfg, []manifest{{ID: "feed", Name: "Feed", Frontend: "@myapp/plugin-feed"}}))

	if want := "// SPDX-License-Identifier: Apache-2.0\n"; goSrc[:len(want)] != want {
		t.Errorf("generateGo() header = %q, want the License field %q", goSrc[:len(want)], want)
	}
	if want := "// SPDX-License-Identifier: AGPL-3.0-or-later\n"; tsSrc[:len(want)] != want {
		t.Errorf("generateTS() header = %q, want the TSLicense field %q", tsSrc[:len(want)], want)
	}
}

func TestGenerateTSWithoutFrontendPlugins(t *testing.T) {
	t.Parallel()

	got := string(generateTS(testConfig, []manifest{
		{ID: "headless", Name: "Headless", Backend: "example.com/headless"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

import type { FrontendPlugin } from '@myapp/frontend-sdk'

export const plugins: FrontendPlugin[] = []
`
	if got != want {
		t.Errorf("generateTS() = %q, want %q", got, want)
	}
}

func TestGenerateRegistryRendersEveryBackend(t *testing.T) {
	t.Parallel()

	cfg := testConfig
	cfg.GoRegistryPath = "internal/graphroot/registry_gen.go"
	cfg.GoRegistryPackage = "graphroot"

	got := string(generateRegistry(cfg, []manifest{
		{ID: "photo-gallery", Name: "Photo Gallery", Backend: "example.com/gallery"},
		{ID: "feed", Name: "Feed", Backend: "example.com/myapp/plugins/feed", Frontend: "@myapp/plugin-feed"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	photo_gallery "example.com/gallery"
	feed "example.com/myapp/plugins/feed"

	"example.com/myapp/sdk"
)

// All registers every plugin and returns them in registration order.
func All(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 2)
	photo_galleryPlugin, err := photo_gallery.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, photo_galleryPlugin)
	feedPlugin, err := feed.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, feedPlugin)
	return plugins, nil
}
`
	if got != want {
		t.Errorf("generateRegistry() = %q, want %q", got, want)
	}
}

func TestGenerateRegistryWithoutBackendPlugins(t *testing.T) {
	t.Parallel()

	cfg := testConfig
	cfg.GoRegistryPath = "internal/graphroot/registry_gen.go"
	cfg.GoRegistryPackage = "graphroot"

	got := string(generateRegistry(cfg, []manifest{
		{ID: "pretty", Name: "Pretty", Frontend: "@myapp/plugin-pretty"},
	}))

	want := `// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package graphroot

import (
	"example.com/myapp/sdk"
)

// All registers every plugin and returns them in registration order.
func All(_ sdk.Deps) ([]sdk.Plugin, error) {
	return []sdk.Plugin{}, nil
}
`
	if got != want {
		t.Errorf("generateRegistry() = %q, want %q", got, want)
	}
}

func TestRunWritesTheRegistryWhenConfigured(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	for _, dir := range []string{"cmd/myapp", "frontend/src/plugins", "internal/graphroot"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}
	cfg := testConfig
	cfg.GoRegistryPath = "internal/graphroot/registry_gen.go"
	cfg.GoRegistryPackage = "graphroot"

	if err := Run(root, cfg); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}

	registry, err := os.ReadFile(filepath.Join(root, "internal", "graphroot", "registry_gen.go"))
	if err != nil {
		t.Fatalf("reading the generated registry: %v", err)
	}
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if string(registry) != string(generateRegistry(cfg, manifests)) {
		t.Errorf("registry_gen.go = %q, want the generated registry", registry)
	}
}

func TestRunSkipsTheRegistryWhenUnset(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	for _, dir := range []string{"cmd/myapp", "frontend/src/plugins", "internal/graphroot"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}

	if err := Run(root, testConfig); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}

	if _, err := os.Stat(filepath.Join(root, "internal", "graphroot", "registry_gen.go")); !os.IsNotExist(err) {
		t.Errorf("registry_gen.go exists without registry config, stat error = %v", err)
	}
}

func TestRunRejectsAHalfConfiguredRegistry(t *testing.T) {
	t.Parallel()

	tests := map[string]func(cfg Config) Config{
		"path without package": func(cfg Config) Config {
			cfg.GoRegistryPath = "internal/graphroot/registry_gen.go"
			return cfg
		},
		"package without path": func(cfg Config) Config {
			cfg.GoRegistryPackage = "graphroot"
			return cfg
		},
	}

	for testName, mutate := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, "feed", feedManifest)
			for _, dir := range []string{"cmd/myapp", "frontend/src/plugins", "internal/graphroot"} {
				if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
					t.Fatalf("creating %s: %v", dir, err)
				}
			}

			if err := Run(root, mutate(testConfig)); err == nil {
				t.Fatal("Run() error = nil, want a config validation error")
			}
		})
	}
}

func TestRunWritesWiringFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	for _, dir := range []string{"cmd/myapp", "frontend/src/plugins"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}

	if err := Run(root, testConfig); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}

	goSrc, err := os.ReadFile(filepath.Join(root, "cmd", "myapp", "plugins_gen.go"))
	if err != nil {
		t.Fatalf("reading generated Go wiring: %v", err)
	}
	tsSrc, err := os.ReadFile(filepath.Join(root, "frontend", "src", "plugins", "index.ts"))
	if err != nil {
		t.Fatalf("reading generated TS wiring: %v", err)
	}
	manifests, err := loadManifests(filepath.Join(root, "plugins"))
	if err != nil {
		t.Fatalf("loadManifests() error = %v, want nil", err)
	}
	if string(goSrc) != string(generateGo(testConfig, manifests)) {
		t.Errorf("plugins_gen.go = %q, want the generated wiring", goSrc)
	}
	if string(tsSrc) != string(generateTS(testConfig, manifests)) {
		t.Errorf("index.ts = %q, want the generated registry", tsSrc)
	}
}

func TestRunScansEveryRootInOrder(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	writePluginIn(t, root, "enterprise", "tenancy",
		`{"id": "tenancy", "name": "Tenancy", "backend": "example.com/enterprise/tenancy"}`)
	for _, dir := range []string{"cmd/myapp", "frontend/src/plugins"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("creating %s: %v", dir, err)
		}
	}
	cfg := testConfig
	cfg.Roots = []string{"plugins", "enterprise"}

	if err := Run(root, cfg); err != nil {
		t.Fatalf("Run() error = %v, want nil", err)
	}

	goSrc, err := os.ReadFile(filepath.Join(root, "cmd", "myapp", "plugins_gen.go"))
	if err != nil {
		t.Fatalf("reading generated Go wiring: %v", err)
	}
	feedAt := strings.Index(string(goSrc), "example.com/myapp/plugins/feed")
	tenancyAt := strings.Index(string(goSrc), "example.com/enterprise/tenancy")
	if feedAt < 0 || tenancyAt < 0 {
		t.Fatalf("plugins_gen.go = %q, want imports from both roots", goSrc)
	}
	if feedAt > tenancyAt {
		t.Errorf("plugins_gen.go orders the enterprise root before plugins, want root order")
	}
}

func TestRunEmptySecondRootReproducesDefaultBytes(t *testing.T) {
	t.Parallel()

	defaultRoot := t.TempDir()
	overlayRoot := t.TempDir()
	for _, root := range []string{defaultRoot, overlayRoot} {
		writePlugin(t, root, "feed", feedManifest)
		for _, dir := range []string{"cmd/myapp", "frontend/src/plugins"} {
			if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
				t.Fatalf("creating %s: %v", dir, err)
			}
		}
	}
	if err := os.MkdirAll(filepath.Join(overlayRoot, "enterprise"), 0o755); err != nil {
		t.Fatalf("creating the empty enterprise root: %v", err)
	}
	readme := filepath.Join(overlayRoot, "enterprise", "README.md")
	if err := os.WriteFile(readme, []byte("enterprise plugins land here"), 0o644); err != nil {
		t.Fatalf("writing the enterprise README: %v", err)
	}
	overlayConfig := testConfig
	overlayConfig.Roots = []string{"plugins", "enterprise"}

	if err := Run(defaultRoot, testConfig); err != nil {
		t.Fatalf("Run() with the default root: %v", err)
	}
	if err := Run(overlayRoot, overlayConfig); err != nil {
		t.Fatalf("Run() with the empty enterprise root: %v", err)
	}

	for _, generated := range []string{"cmd/myapp/plugins_gen.go", "frontend/src/plugins/index.ts"} {
		defaultBytes, err := os.ReadFile(filepath.Join(defaultRoot, filepath.FromSlash(generated)))
		if err != nil {
			t.Fatalf("reading %s from the default run: %v", generated, err)
		}
		overlayBytes, err := os.ReadFile(filepath.Join(overlayRoot, filepath.FromSlash(generated)))
		if err != nil {
			t.Fatalf("reading %s from the overlay run: %v", generated, err)
		}
		if string(defaultBytes) != string(overlayBytes) {
			t.Errorf("%s differs between the default and the empty enterprise root", generated)
		}
	}
}

func TestRunRejectsDuplicateIDAcrossRoots(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writePlugin(t, root, "feed", feedManifest)
	writePluginIn(t, root, "enterprise", "feed", feedManifest)
	cfg := testConfig
	cfg.Roots = []string{"plugins", "enterprise"}

	err := Run(root, cfg)

	if err == nil {
		t.Fatal("Run() error = nil, want a duplicate id error")
	}
	if !strings.Contains(err.Error(), "feed") {
		t.Errorf("error = %q, want it to name the duplicated id", err)
	}
}

func TestRunRejectsIncompleteConfig(t *testing.T) {
	t.Parallel()

	tests := map[string]func(cfg Config) Config{
		"missing sdk import":     func(cfg Config) Config { cfg.SDKImport = ""; return cfg },
		"missing frontend sdk":   func(cfg Config) Config { cfg.FrontendSDK = ""; return cfg },
		"missing go wiring path": func(cfg Config) Config { cfg.GoWiringPath = ""; return cfg },
		"missing ts wiring path": func(cfg Config) Config { cfg.TSWiringPath = ""; return cfg },
		"missing license":        func(cfg Config) Config { cfg.License = ""; return cfg },
	}

	for testName, mutate := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writePlugin(t, root, "feed", feedManifest)

			if err := Run(root, mutate(testConfig)); err == nil {
				t.Fatal("Run() error = nil, want a config validation error")
			}
		})
	}
}

func TestRunReportsFailures(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		roots   []string
		prepare func(t *testing.T, root string)
	}{
		"missing plugins directory": {
			prepare: func(_ *testing.T, _ string) {},
		},
		"missing named root": {
			roots: []string{"plugins", "enterprise"},
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "feed", feedManifest)
				for _, dir := range []string{"cmd/myapp", "frontend/src/plugins"} {
					if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
						t.Fatalf("creating %s: %v", dir, err)
					}
				}
			},
		},
		"unwritable go wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "feed", feedManifest)
			},
		},
		"unwritable ts wiring": {
			prepare: func(t *testing.T, root string) {
				writePlugin(t, root, "feed", feedManifest)
				if err := os.MkdirAll(filepath.Join(root, "cmd", "myapp"), 0o755); err != nil {
					t.Fatalf("creating cmd/myapp: %v", err)
				}
			},
		},
	}

	for testName, tc := range tests {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			tc.prepare(t, root)
			cfg := testConfig
			cfg.Roots = tc.roots

			if err := Run(root, cfg); err == nil {
				t.Fatal("Run() error = nil, want an error")
			}
		})
	}
}
